Add Alarm model and refactor Partition
PI1-2018-2/smart-medicine-cup pull request #17
Opened 2018-11-22 21:55 UTC by gabrielziegler3

Signed-off-by: Gabriel Ziegler <gabrielziegler3@gmail.com>

2018-11-22 23:31 UTC, gabrielziegler3 commented
note: run `docker-compose down --volumes` and `docker-compose build` again

2018-11-24 19:49 UTC, icaropires requested changes

2018-11-24 19:49 UTC, icaropires commented on smart_medicine_cup_backend/smc/models.py
> +    # Duration
Comentário desnecessário do duration.

2018-11-24 19:49 UTC, icaropires commented on smart_medicine_cup_backend/smc/models.py
> +    cup = models.ForeignKey("Cup", on_delete=models.CASCADE)
Record não deveria ter relacionamento direto com cup, pois já possui um indireto através de alarm.

2018-11-24 19:55 UTC, icaropires approved these changes

2018-11-24 19:55 UTC, merged