[WIP] End point
PI1-2018-2/smart-medicine-cup pull request #22
Opened 2018-11-25 01:49 UTC by gabrielziegler3

2018-11-25 15:28 UTC, icaropires requested changes
- [ ] Remover prints
- [ ] Remover mudanças feitas no requirements.py e settings.py
- [ ] Responder requisições de forma adequada  (O formato da resposta não está correto e códigos de erro deveriam ser retornardos em caso de exceções)
- [ ] Setar fuso horário correto

2018-11-25 15:56 UTC, gabrielziegler3 commented
O ipython eh para o melhor uso do manage.py shell, o settings.py como estava antes nao funciona por nao ter nenhum ALLOWED_HOSTS e o django_extensions estava instalado no requirementes, mas precisa ser listado no settings.py. Quanto aos prints e ao fuso, os farei.

2018-11-27 01:08 UTC, icaropires requested changes
Faltou:
- [ ] Alterar 204 para 404 e adicionar explicações no corpo da requisição
- [ ] Adicionar o corpo da requisição em caso de erros
- [ ] Retornar 415 se o Content-Type for diferente de application/json
- [ ] Checar se está sendo retornado 405 em caso do método diferente de POST e se não estiver, fazer retornar
- [ ] Em caso de Error ao realizar o parser do JSON, retornar 400 (Lembre-se da exceção KeyError nos dict)
- [ ] Em todos os tipos de evento o objetivo final é a criação de um registro no banco, então deveria ser retornado 201 em caso de sucesso
- [ ] Por que atualizar o alarme caso o usuário tome o remédio?

2018-12-02 19:45 UTC, icaropires approved these changes

2018-12-02 20:18 UTC, merged